import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/providers/toastProvider";
import Providers from "@/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang='en'>
			<body>
				<Providers>
					<ToastProvider />
					{children}
				</Providers>
			</body>
		</html>
	);
}
